input:
    ground_state:
        k_grid:
            sampling: [1, 2, 3]
        n_states: 15
        occupied_part: 0.5

output:
    spectrum:
        energy_interval: [1.0, 2.0]
        n_sampling: 1500
        peak:
            width: 0.002
            form: gauss
