n_k_points: 6
n_occupied_total: 3
n_unoccupied_total: 9
n_isdf_vexc: 3
n_isdf_wscr_occupied: 4
n_isdf_wscr_unoccupied: 5
max_lanczos_iterations: 200
omega_range: [1.0, 2.0]
n_omega: 1500
max_cvt_iterations: 1000
cvt_convergence_criterium: 1.e-5
seed_source: clock