
add_subdirectory(constants)
add_subdirectory(config)
add_subdirectory(dataProcessing)
add_subdirectory(physics)
add_subdirectory(utils)

# add_library(flash src/flash.cpp)

# target_link_libraries(flash 
#         PUBLIC
#             constants 
#             dataProcessing
#             config
# )